Add more testing and restrictions to patient's fields
AY2223S1-CS2103T-W16-3/tp pull request #105
Opened 2022-10-25 09:20 UTC by PeiYee88

Add test-cases to
1. `Parsers` for `get /hw` `get /nok` `get /appton`
2. `Patient's field Predicate` for `hospital wing` `appointment by date predicate`

Restricts hospital wing to only accept values of {east, west, south, north; case-insensitive} only

Reconsider implementation of AppointmentByDatePredicate to include cases where past appointments is null

`get /nok` accepts multiple inputs
`get /hw` accepts only one input
`get /appton` accepts multiple inputs : which allows medical staffs to be able to retrieve multiple appointment dates in a single command

2022-10-25 15:35 UTC, nehcuy requested changes
I think there are better ways to handle hospital wing restrictions. It would be better if we rethink the logic through the processing of user inputs. :) I've wrote up the possible changes to make the implementation seem more consistent with the rest of the codebase.

2022-10-26 13:54 UTC, PeiYee88 commented on src/main/java/seedu/address/model/person/HospitalWing.java
> +        },
no need semicolon

2022-10-26 13:54 UTC, PeiYee88 commented on src/main/java/seedu/address/model/person/AppointmentByDatePredicate.java
>      }
edited! thanks for spoting it out!

2022-10-26 19:37 UTC, merged

2022-10-26 22:57 UTC, nehcuy commented on src/main/java/seedu/address/model/person/HospitalWing.java
>      }
Apologies, there seems to be some errors caused by this. Fixed in PR #116.